# Introdução básica de álgebra linear

**Tópicos**
* Noções de vetores
* Noção de matrizes.
* Espaços vetoriais.
* Transformações lineares.
* 


**Referências Bibliográficas**
* Anton, H. e Rorres, C. Álgebra Linear com Aplicações. Bookman, 8ª Edição, 2001;
* Boldrini, J. L., Costa, S. I. R., Figueiredo, V. L. e Wetzler, H. G. Álgebra Linear. Editora Harbra, 3ª Edição, 1986;
* Callioli, C. A., Domingues, H. H. e Costa, R. F. Álgebra Linear e Aplicações. Atual Editora, 6ª Edição, 1990;
* Franco, N. B. Cálculo Numérico. Pearson Education, 1ª edição, 2007;
* Ruggiero, M. A. G. e Lopes, V. L. da R. Cálculo Numérico - Aspectos Teóricos e Computacionais. Makron Books, 2ª Edição, 1996;
* Strang, G. Introduction to Linear Algebra. Wellesley-Cambridge Press. Third Edition, 2003;
* Strang, G. Linear Algebra and Its Applications. Thomson, Fourth Edition, 2006;
* Pulino, P. Álgebra Linear e Suas Aplicações: Notas de Aula. 2012. Disponível em: http://www.ime.unicamp.br/~pulino/ALESA/Texto/;
* Watkins, D. S. Fundamentals of Matrix Computations. John Wiley & Sons, Third Edition, 2002.

**Recursos Online**
* [Machine Learning with Python Cookbook by Chris Albon (Chapter 1. Vectors, Matrices, and Arrays.)](https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html)
* [Linear Algebra with SciPy.](https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/)
* [Scipy Lecture Notes.](https://scipy-lectures.org/index.html)
* [1.3.1. The NumPy array object.](https://scipy-lectures.org/intro/numpy/array_object.html#numpy-arrays)
* [3.2. Sympy : Symbolic Mathematics in Python.](https://scipy-lectures.org/packages/sympy.html#matrices)
* [MPR213 Lecture notes - Algebra demos.](https://github.com/mpr213/lecture-notes/blob/master/Extra_01_Algebra_Demo.ipynb)
* [Profa Marcia Ruggiero - Álgebra Linear e Aplicações.](https://www.ime.unicamp.br/~marcia/AlgebraLinear/)

In [41]:
import numpy as np
import scipy as sp
import pandas as pd
import numpy.linalg as la
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import os

# Noções de vetores

Nesta seção apresentamos uma rápida revisão sobre vetores e como trabalhar com eles em Python. Para definir vetores utilizamos a função array do numpy. Abaixo um exemplo.

In [54]:
v1 = np.array([1, 2, 3])
v2 = np.array([1, -3, 2])

# Definindo o vetor v3 como a soma dos vetores v1 e v2.
v3 = v1 + v2

v3

array([ 2, -1,  5])

## Multiplicação das coordenadas

A linguagem python tem a propriedade de realizar a seguinte operação entre os vetores $v_1 = (a_1,a_2,a_3)$ e $v_2 = (b_1,b_2,b_3)$ 


\begin{equation}
\nonumber v_1 * v_2 = (a_1 b_1, a_2 b_2, a_3 b_3)
\end{equation}

Abaixo um exemplo deste tipo de operação.

In [57]:
v1 = np.array([1, 2, 4])
v2 = np.array([0,-2,-1])

v1 * v2

array([ 0, -4, -4])

## Divisão das coordenadas

Da mesma forma que o Python realiza multiplicação de coordenadas, também pode realizar a divisão de suas coordenadas. Seja dois vetores $v_1 = (a_1,a_2,a_3)$ e $v_2 = (b_1,b_2,b_3)$ a divisão entre suas coordenadas é dada por

\begin{equation}
\nonumber v_1 / v_2 = (a_1 / b_1, a_2 / b_2, a_3 / b_3)
\end{equation}

Abaixo um exemplo deste tipo de operação.

In [58]:
v1 = np.array([9, 21, 16])
v2 = np.array([3,-7,-2])

v1 / v2

array([ 3., -3., -8.])

## Produto escalar

Dado dois vetores $v_1 = (a_1,a_2,a_3)$ e $v_2 = (b_1,b_2,b_3)$ o produto escalar entre estes dois vetores é dado por

\begin{equation}
\nonumber v_1 \cdot v_2 = a_1b_1 + a_2 b_2 + a_3 b_3
\end{equation}

Abaixo um exemplo de produto escalar entre vetores.

In [56]:
v1 = np.array([1, 2, 4])
v2 = np.array([0,-2,-1])

np.dot(v1, v2)

-8

## Produto vetorial

In [6]:
vector1 = np.array([2, 4, 6])
vector2 = np.array([1, 1, 1])
print(msg.format('cross', vector1, vector2, np.cross(vector1, vector2)))

The cross product of [2 4 6] and [1 1 1] is [-2  4 -2].


# Noção de matrizes

# Auto vetores e auto valores

In [64]:
A = np.array([[ 1, -1,  0,  0,  0],
              [-1,  2, -2,  0,  0],
              [ 0, -2,  2, -2,  0],
              [ 0,  0, -2,  2, -2],
              [ 0,  0,  0, -2,  2]])

b = np.array([1, 1, 1, 1, 1])

x = la.solve(A, b)

x

array([ 1. , -0. , -1. , -1.5, -1. ])

In [68]:
lam,v = la.eig(A)

np.dot(A, v[:, 0])

array([-0.23470083, -0.54079707, -0.77609977, -0.74139641, -0.44876034])

In [71]:
v[0]

# Tente imprimir também as 

array([ 0.17995803, -0.63787995, -0.69897478,  0.09269383, -0.25212376])

In [13]:
lam = la.eig(A)

print("Determining the eigen values (A - lambda*I)*v = 0")
print("The eigen values of\n", A, "\nare", lam)
print("\nThe corresponding eigen vectors are\n", v)
print("\nQuick Test:\n", "(A*v = lambda*v):\n", np.dot(A, v[:, 0]), "=\n", lam[0] * v[:, 0])

Determining the eigen values (A - lambda*I)*v = 0
The eigen values of
 [[ 1 -1  0  0  0]
 [-1  2 -2  0  0]
 [ 0 -2  2 -2  0]
 [ 0  0 -2  2 -2]
 [ 0  0  0 -2  2]] 
are (array([-1.30419756,  0.24599833,  1.39419206,  5.270692  ,  3.39331517]), array([[ 0.17995803, -0.63787995, -0.69897478,  0.09269383, -0.25212376],
       [ 0.41465886, -0.48096255,  0.27553031, -0.39586681,  0.60341162],
       [ 0.59507838, -0.10286458,  0.43294661,  0.60103229, -0.2943094 ],
       [ 0.5684694 ,  0.39075022, -0.14438906, -0.58702894, -0.39837874],
       [ 0.34408923,  0.44555285, -0.47668263,  0.35896314,  0.57184297]]))

The corresponding eigen vectors are
 [[ 0.17995803 -0.63787995 -0.69897478  0.09269383 -0.25212376]
 [ 0.41465886 -0.48096255  0.27553031 -0.39586681  0.60341162]
 [ 0.59507838 -0.10286458  0.43294661  0.60103229 -0.2943094 ]
 [ 0.5684694   0.39075022 -0.14438906 -0.58702894 -0.39837874]
 [ 0.34408923  0.44555285 -0.47668263  0.35896314  0.57184297]]

Quick Test:
 (A*v = lambda*v):


In [66]:
lam = la.eig(A)

print("Determining the eigen values (A - lambda*I)*v = 0")
print("The eigen values of\n", A, "\nare", lam)
print("\nThe corresponding eigen vectors are\n", v)
print("\nQuick Test:\n", "(A*v = lambda*v):\n", np.dot(A, v[:, 0]), "=\n", lam[0] * v[:, 0])

Determining the eigen values (A - lambda*I)*v = 0
The eigen values of
 [[ 1 -1  0  0  0]
 [-1  2 -2  0  0]
 [ 0 -2  2 -2  0]
 [ 0  0 -2  2 -2]
 [ 0  0  0 -2  2]] 
are (array([-1.30419756,  0.24599833,  1.39419206,  5.270692  ,  3.39331517]), array([[ 0.17995803, -0.63787995, -0.69897478,  0.09269383, -0.25212376],
       [ 0.41465886, -0.48096255,  0.27553031, -0.39586681,  0.60341162],
       [ 0.59507838, -0.10286458,  0.43294661,  0.60103229, -0.2943094 ],
       [ 0.5684694 ,  0.39075022, -0.14438906, -0.58702894, -0.39837874],
       [ 0.34408923,  0.44555285, -0.47668263,  0.35896314,  0.57184297]]))

The corresponding eigen vectors are
 [ 4 -2  2]


IndexError: too many indices for array